version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: viatab
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./ViaTab.Backend
    ports:
      - "5001:8080"
    depends_on:
      - postgres
    environment:
      - DB_CONNECTION=Host=postgres;Port=5432;Database=viatab;Username=postgres;Password=postgres123

volumes:
  postgres_data: