apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2                    # 2 backend pods for load balancing!
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: viatab-backend:latest    # Our Docker image
        imagePullPolicy: Never          # Use local image (required for assignment)
        env:
        - name: DB_CONNECTION
          value: "Host=postgres-service;Port=5432;Database=viatab;Username=postgres;Password=postgres123"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort              # Exposes service outside cluster
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080           # Access via localhost:30080